#!/usr/bin/env bash
# installs and Configures HAproxy on ubuntu machine

apt-get update
apt-get -y install haproxy

echo "
frontend  kevcare-frontend
        bind *:80
        mode http
        default_backend kevcare-backend
backend kevcare-backend
        balance roundrobin
        server web-01 54.234.70.95:80 check
        server web-02 100.26.235.121:80 check" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | tee -a /etc/default/haproxy

service haproxy restart
